Bookstore API PR
kkasaija/Bookstore pull request #4
Opened 2022-11-17 13:14 UTC by Kasaija-Kenneth

- [x] Used useSelector to consume the state.
- [x] Imported Redux Provider and store in the main component of React app.
- [x] Imported Redux useDispatch.
- [x] Used `fetch` with `createAsyncThunk` for making API calls.
- [x] Fetched book list from Bookstore API on Books page load
- [x] Refactored `add book` and `remove book` features to persist changes in the server.

2022-11-17 16:50 UTC, Munsa1 requested changes
Hi @Kasaija-Kenneth , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._
- [ ] `createAsyncThunk` is to be used in the project for creating thunk action creators: Take a look at the screenshot below
![image](https://user-images.githubusercontent.com/81932478/202507202-80946eef-fe45-4be9-82c1-7499ad409fa8.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 16:50 UTC, Munsa1 commented on src/redux/books/books.js
> +  })
- [ ] It is a requirement that `createAsyncThunk` is used in the project for creating thunk action creators: Kindly fix this issue
Example


`
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios'; 


export const getBooks = createAsyncThunk(
  'books/getBooks',
  async () => {
    const response = await axios.get(
      'https://us-central1-bookstore-api-e63c8.cloudfunctions.net/bookstoreApi/',
    );
    return response.data;
  },
); 
`

2022-11-18 12:06 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @Kasaija-Kenneth , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**Kindly check an optional comment I left under the review**_ :pray: 

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Git Flow. :heavy_check_mark: 
-   App worked as expected. :heavy_check_mark: 

![](https://camo.githubusercontent.com/f4e04d5e9518e3cbf972fb0f7611848a87ed4e1aa7770811bc22c5b957824887/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c3253716972355a78666f5332374576532f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-18 12:16 UTC, Kasaija-Kenneth commented
Thank you

2022-11-18 12:16 UTC, merged